"""add_user_preference_columns

Revision ID: 53cfd16ba7a2
Revises: 009_prod_hardening
Create Date: 2026-04-18 20:54:11.654983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53cfd16ba7a2'
down_revision: Union[str, None] = '009_prod_hardening'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exchange_credentials', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=36).with_variant(sa.UUID(), 'postgresql'),
               existing_nullable=False)
    op.alter_column('exchange_credentials', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=36).with_variant(sa.UUID(), 'postgresql'),
               existing_nullable=False)
    op.alter_column('exchange_credentials', 'exchange',
               existing_type=sa.VARCHAR(length=50),
               comment='binance | alpaca',
               existing_nullable=False)
    op.alter_column('exchange_credentials', 'additional_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               existing_nullable=True)
    op.add_column('funding_transactions', sa.Column('zar_amount', sa.Numeric(precision=20, scale=2), nullable=False))
    op.add_column('funding_transactions', sa.Column('fx_rate_used', sa.Numeric(precision=20, scale=8), nullable=True))
    op.add_column('funding_transactions', sa.Column('usd_amount', sa.Numeric(precision=20, scale=8), nullable=True))
    op.alter_column('funding_transactions', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=36).with_variant(sa.UUID(), 'postgresql'),
               existing_nullable=False)
    op.alter_column('funding_transactions', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=36).with_variant(sa.UUID(), 'postgresql'),
               existing_nullable=False)
    op.alter_column('funding_transactions', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='pending | confirmed | credited | liquidating | processing | completed | failed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_column('funding_transactions', 'exchange_rate')
    op.drop_column('funding_transactions', 'amount_zar')
    op.drop_column('funding_transactions', 'exchange_amount')
    op.alter_column('global_state', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Single-row global state identifier',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('global_state', 'shared_reservoir_balance',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               comment=None,
               existing_comment='Tier 1 — BlackRock BUIDL / T-Bills instant-access spending wallet',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('global_state', 'shared_nursery_balance',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               comment=None,
               existing_comment='USDC stablecoin pool — funds all new $100 seeds',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('global_state', 'vault_tier1_buidl',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               comment=None,
               existing_comment='Vault Tier 1 — BlackRock BUIDL / T-Bills (Reservoir backing)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('global_state', 'vault_tier2_etfs',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               comment=None,
               existing_comment='Vault Tier 2 — Low-cost Index ETFs (VOO / QQQ)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('global_state', 'vault_tier2_capacity',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               comment=None,
               existing_comment='Tier 2 saturation cap — overflow routes to Tier 3 after this amount',
               existing_nullable=False,
               existing_server_default=sa.text('50000'))
    op.alter_column('global_state', 'vault_tier3_real_estate',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               comment=None,
               existing_comment='Vault Tier 3 — Tokenized Real Estate (RealT / Centrifuge)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('global_state', 'last_heartbeat',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='User activity heartbeat — triggers Legacy Protocol at 180 days inactive',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('global_state', 'legacy_heir_wallet',
               existing_type=sa.VARCHAR(length=256),
               comment=None,
               existing_comment='Pre-designated heir wallet address for Legacy Protocol transfer',
               existing_nullable=True)
    op.alter_column('global_state', 'legacy_trust_contract',
               existing_type=sa.VARCHAR(length=256),
               comment=None,
               existing_comment='Family Trust Smart Contract address for Tier 2/3 assets',
               existing_nullable=True)
    op.alter_column('global_state', 'legacy_triggered',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment="Whether the Legacy Protocol (Dead Man's Switch) has been activated",
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('global_state', 'kill_switch_status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Engine status: active | paused | global_pause',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('global_state', 'strike_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Fleet-wide consecutive underperformance counter (0-3, triggers Global Pause at 3)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('global_state', 'preflight_passed',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether current configuration has passed Pre-Flight Simulation',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('global_state', 'tax_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               comment=None,
               existing_comment='Default tax reserve rate applied during waterfall distribution',
               existing_nullable=False,
               existing_server_default=sa.text('0.3000'))
    op.alter_column('global_state', 'boost_log',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Array of boost events: [{type, amount, timestamp}]',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('global_state', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Row creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('global_state', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last modification timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('invite_codes', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=36).with_variant(sa.UUID(), 'postgresql'),
               existing_nullable=False)
    op.alter_column('invite_codes', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=36).with_variant(sa.UUID(), 'postgresql'),
               existing_nullable=False)
    op.alter_column('invite_codes', 'claimed_by',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=36).with_variant(sa.UUID(), 'postgresql'),
               existing_nullable=True)
    op.alter_column('seeds', 'seed_id',
               existing_type=sa.VARCHAR(length=50),
               comment="Human-readable ID like 'seed_001_042'",
               existing_nullable=False)
    op.alter_column('seeds', 'stage',
               existing_type=sa.INTEGER(),
               comment='Scaling stage (1-4)',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('seeds', 'strategy',
               existing_type=sa.VARCHAR(length=30),
               comment='momentum | exploratory | dumb_baseline | llm',
               existing_nullable=False,
               existing_server_default=sa.text("'momentum'::character varying"))
    op.alter_column('seeds', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='active | paused | ground_zero | pruned | closed',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('trees', 'tree_id',
               existing_type=sa.VARCHAR(length=50),
               comment="Human-readable ID like 'tree_001'",
               existing_nullable=False)
    op.alter_column('trees', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=36).with_variant(sa.UUID(), 'postgresql'),
               nullable=False)
    op.alter_column('trees', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='active | paused',
               existing_nullable=False,
               existing_server_default=sa.text("'paused'::character varying"))
    op.alter_column('user_forest_state', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=36).with_variant(sa.UUID(), 'postgresql'),
               existing_nullable=False)
    op.alter_column('user_forest_state', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=36).with_variant(sa.UUID(), 'postgresql'),
               existing_nullable=False)
    op.alter_column('user_forest_state', 'kill_switch_status',
               existing_type=sa.VARCHAR(length=20),
               comment='active | paused | global_pause',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('user_forest_state', 'total_platform_fees_paid',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               comment='Cumulative 5% platform fees paid by this member to the Master.',
               existing_nullable=False,
               existing_server_default=sa.text('0.0'))
    op.add_column('users', sa.Column('telegram_alerts_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('ground_zero_alerts_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('trade_signals_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.alter_column('users', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=36).with_variant(sa.UUID(), 'postgresql'),
               existing_nullable=False)
    op.alter_column('users', 'invited_by',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=36).with_variant(sa.UUID(), 'postgresql'),
               existing_nullable=True)
    op.alter_column('users', 'platform_fee_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               comment='Master can adjust this per-user. 0.05 is 5%.',
               existing_nullable=False,
               existing_server_default=sa.text('0.0500'))
    op.alter_column('users', 'deposit_reference',
               existing_type=sa.VARCHAR(length=20),
               comment='Unique EFT reference e.g., WE-ARN0042',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'deposit_reference',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Unique EFT reference e.g., WE-ARN0042',
               existing_nullable=True)
    op.alter_column('users', 'platform_fee_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               comment=None,
               existing_comment='Master can adjust this per-user. 0.05 is 5%.',
               existing_nullable=False,
               existing_server_default=sa.text('0.0500'))
    op.alter_column('users', 'invited_by',
               existing_type=sa.String(length=36).with_variant(sa.UUID(), 'postgresql'),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.String(length=36).with_variant(sa.UUID(), 'postgresql'),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_column('users', 'trade_signals_enabled')
    op.drop_column('users', 'ground_zero_alerts_enabled')
    op.drop_column('users', 'telegram_alerts_enabled')
    op.alter_column('user_forest_state', 'total_platform_fees_paid',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               comment=None,
               existing_comment='Cumulative 5% platform fees paid by this member to the Master.',
               existing_nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('user_forest_state', 'kill_switch_status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='active | paused | global_pause',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('user_forest_state', 'user_id',
               existing_type=sa.String(length=36).with_variant(sa.UUID(), 'postgresql'),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('user_forest_state', 'id',
               existing_type=sa.String(length=36).with_variant(sa.UUID(), 'postgresql'),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('trees', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='active | paused',
               existing_nullable=False,
               existing_server_default=sa.text("'paused'::character varying"))
    op.alter_column('trees', 'user_id',
               existing_type=sa.String(length=36).with_variant(sa.UUID(), 'postgresql'),
               type_=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('trees', 'tree_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Human-readable ID like 'tree_001'",
               existing_nullable=False)
    op.alter_column('seeds', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='active | paused | ground_zero | pruned | closed',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('seeds', 'strategy',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='momentum | exploratory | dumb_baseline | llm',
               existing_nullable=False,
               existing_server_default=sa.text("'momentum'::character varying"))
    op.alter_column('seeds', 'stage',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Scaling stage (1-4)',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('seeds', 'seed_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Human-readable ID like 'seed_001_042'",
               existing_nullable=False)
    op.alter_column('invite_codes', 'claimed_by',
               existing_type=sa.String(length=36).with_variant(sa.UUID(), 'postgresql'),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('invite_codes', 'created_by',
               existing_type=sa.String(length=36).with_variant(sa.UUID(), 'postgresql'),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('invite_codes', 'id',
               existing_type=sa.String(length=36).with_variant(sa.UUID(), 'postgresql'),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('global_state', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last modification timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('global_state', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Row creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('global_state', 'boost_log',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Array of boost events: [{type, amount, timestamp}]',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('global_state', 'tax_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               comment='Default tax reserve rate applied during waterfall distribution',
               existing_nullable=False,
               existing_server_default=sa.text('0.3000'))
    op.alter_column('global_state', 'preflight_passed',
               existing_type=sa.BOOLEAN(),
               comment='Whether current configuration has passed Pre-Flight Simulation',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('global_state', 'strike_count',
               existing_type=sa.INTEGER(),
               comment='Fleet-wide consecutive underperformance counter (0-3, triggers Global Pause at 3)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('global_state', 'kill_switch_status',
               existing_type=sa.VARCHAR(length=20),
               comment='Engine status: active | paused | global_pause',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('global_state', 'legacy_triggered',
               existing_type=sa.BOOLEAN(),
               comment="Whether the Legacy Protocol (Dead Man's Switch) has been activated",
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('global_state', 'legacy_trust_contract',
               existing_type=sa.VARCHAR(length=256),
               comment='Family Trust Smart Contract address for Tier 2/3 assets',
               existing_nullable=True)
    op.alter_column('global_state', 'legacy_heir_wallet',
               existing_type=sa.VARCHAR(length=256),
               comment='Pre-designated heir wallet address for Legacy Protocol transfer',
               existing_nullable=True)
    op.alter_column('global_state', 'last_heartbeat',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='User activity heartbeat — triggers Legacy Protocol at 180 days inactive',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('global_state', 'vault_tier3_real_estate',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               comment='Vault Tier 3 — Tokenized Real Estate (RealT / Centrifuge)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('global_state', 'vault_tier2_capacity',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               comment='Tier 2 saturation cap — overflow routes to Tier 3 after this amount',
               existing_nullable=False,
               existing_server_default=sa.text('50000'))
    op.alter_column('global_state', 'vault_tier2_etfs',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               comment='Vault Tier 2 — Low-cost Index ETFs (VOO / QQQ)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('global_state', 'vault_tier1_buidl',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               comment='Vault Tier 1 — BlackRock BUIDL / T-Bills (Reservoir backing)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('global_state', 'shared_nursery_balance',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               comment='USDC stablecoin pool — funds all new $100 seeds',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('global_state', 'shared_reservoir_balance',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               comment='Tier 1 — BlackRock BUIDL / T-Bills instant-access spending wallet',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('global_state', 'id',
               existing_type=sa.UUID(),
               comment='Single-row global state identifier',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.add_column('funding_transactions', sa.Column('exchange_amount', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=True))
    op.add_column('funding_transactions', sa.Column('amount_zar', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False))
    op.add_column('funding_transactions', sa.Column('exchange_rate', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=True))
    op.alter_column('funding_transactions', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='pending | confirmed | credited | liquidating | processing | completed | failed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('funding_transactions', 'user_id',
               existing_type=sa.String(length=36).with_variant(sa.UUID(), 'postgresql'),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('funding_transactions', 'id',
               existing_type=sa.String(length=36).with_variant(sa.UUID(), 'postgresql'),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_column('funding_transactions', 'usd_amount')
    op.drop_column('funding_transactions', 'fx_rate_used')
    op.drop_column('funding_transactions', 'zar_amount')
    op.alter_column('exchange_credentials', 'additional_config',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('exchange_credentials', 'exchange',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='binance | alpaca',
               existing_nullable=False)
    op.alter_column('exchange_credentials', 'user_id',
               existing_type=sa.String(length=36).with_variant(sa.UUID(), 'postgresql'),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('exchange_credentials', 'id',
               existing_type=sa.String(length=36).with_variant(sa.UUID(), 'postgresql'),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
